"""36 made-up reviews of school supplies, each with the right label: positive, negative or neutral (a fact, no opinion)."""
REVIEWS = [
    ("The notebook paper is thick and the pen glides smoothly. I love it.", "positive"),
    ("Best backpack I have owned, it still looks new after a whole year.", "positive"),
    ("Great colours, the markers did not bleed through the page at all.", "positive"),
    ("Arrived a day early and the box was perfectly packed. Very happy.", "positive"),
    ("My son uses this calculator every day and says the buttons feel great.", "positive"),
    ("Excellent value, the ruler is sturdy and the markings are easy to read.", "positive"),
    ("The glue stick works wonderfully and does not dry out.", "positive"),
    ("Super comfortable pencil case, it holds everything and the zip is smooth.", "positive"),
    ("Fantastic stapler, I have not had a single jam.", "positive"),
    ("These scissors cut cleanly through everything. Highly recommend.", "positive"),
    ("The lunch box keeps food fresh until noon, my daughter is delighted.", "positive"),
    ("Sharp, bright highlighters that last for months. Worth every cent.", "positive"),
    ("The zipper broke on the second day. Complete waste of money.", "negative"),
    ("Pens ran out of ink within a week and two of them leaked in my bag.", "negative"),
    ("The calculator screen is dim and the buttons stick. Very disappointed.", "negative"),
    ("Packaging was torn, and two notebooks arrived damaged.", "negative"),
    ("The ruler snapped in half the first time my child dropped it.", "negative"),
    ("Terrible glue, nothing sticks and it smells awful.", "negative"),
    ("The backpack straps hurt my shoulders after ten minutes.", "negative"),
    ("Colours look nothing like the picture, and the paint is watery.", "negative"),
    ("The stapler jams every third page. I returned it.", "negative"),
    ("The pencil case fell apart at the seams within a month.", "negative"),
    ("Scissors are blunt, they chew the paper instead of cutting it.", "negative"),
    ("Lunch box lid does not close properly and the juice leaked everywhere.", "negative"),
    ("The package contains twelve pencils and one sharpener.", "neutral"),
    ("This backpack is 40 centimetres tall and has two zip pockets.", "neutral"),
    ("The notebook has 120 pages and a blue cover.", "neutral"),
    ("It is a scientific calculator that runs on one AAA battery.", "neutral"),
    ("The ruler is 30 centimetres long and made of plastic.", "neutral"),
    ("I bought this stapler for my daughter's class. It uses standard staples.", "neutral"),
    ("The markers come in a set of 24 colours with a plastic case.", "neutral"),
    ("This glue stick is 21 grams and says it is washable.", "neutral"),
    ("The lunch box has two compartments and a carrying handle.", "neutral"),
    ("Delivery took five days and the item matched the description.", "neutral"),
    ("The scissors have blue handles and are about 13 centimetres long.", "neutral"),
    ("The pencil case measures 20 by 8 centimetres.", "neutral"),
]
